import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import Image from "next/image";
import "@/app/global.css";

import TopMenu from "@/components/layout/TopMenu";
import Footer from "@/components/layout/Footer";

const inter = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={(inter.className, "bg-bg")}>
        <TopMenu />
        {children}
        <Image
          className="fixed bottom-0 right-0 opacity-5 z-[-1]"
          src="/img/bg-logo.png"
          alt="bg-logo"
          width={500}
          height={500}
        />
        <Footer />
      </body>
    </html>
  );
}
