const TalentData = [
  {
    id: "honey-churros",
    name: "허니츄러스",
    enName: "HoneyChurros",
    personalColor: "#ff8caa",
    xLink: "https://twitter.com/honeychurros1",
    youtubeLink: "https://www.youtube.com/@Honey__Churros",
    twitchLink: "https://www.twitch.tv/honeychurros",
    vedioLId: "PnLzYigLYu8?si=OVar44zRiuPBBfwI",
  },
  {
    id: "ohwayo",
    name: "오화요",
    enName: "Ohwayo",
    personalColor: "#8c8c8c",
    xLink: "https://twitter.com/oi52ohighyo",
    youtubeLink: "https://www.youtube.com/@Ohwayo_Projecti",
    twitchLink: "https://www.twitch.tv/oi52ohighyo",
    vedioLId: "SJDnBrMAVSw?si=kHlXeF9Y71ZMEl67",
  },
  {
    id: "dam-yui",
    name: "담유이",
    enName: "DamYui",
    personalColor: "#79dcfb",
    xLink: "https://twitter.com/damyui_",
    youtubeLink: "https://www.youtube.com/@DamYui_Projecti",
    twitchLink: "https://www.twitch.tv/damyui_pi",
    vedioLId: "00auXfr9Q-Y?si=vFEchSCXnUOilDWC",
  },
  {
    id: "aya-uke",
    name: "아야",
    enName: "AyaUke",
    profileImages: [
      "profile-aya-uke-1",
      "profile-aya-uke-2",
      "profile-aya-uke-3",
    ],
    personalColor: "#cc9ce6",
    xLink: "https://twitter.com/AyaUke_V",
    youtubeLink: "https://www.youtube.com/@AyaUke_Projecti",
    twitchLink: "https://www.twitch.tv/ayauke",
    vedioLId: "7QhAAik3JzU?si=6-0Y8m3f6-DEAOqz",
  },
  {
    id: "mang-nae",
    name: "망내",
    enName: "MangNae",
    personalColor: "#10002c",
    xLink: "https://twitter.com/Mang_nae_",
    youtubeLink: "https://www.youtube.com/@MangNae_Projecti",
    twitchLink: "https://www.twitch.tv/mangnae_pi",
    vedioLId: "8ZkVVRcN678?si=HnFdOMCiOBF1Lbnb",
  },
  {
    id: "ddddragon",
    name: "디디디용",
    enName: "DDDDragon",
    personalColor: "#FFBF00",
    xLink: "https://twitter.com/DDDDragon_",
    youtubeLink: "https://www.youtube.com/@DDDDragon_Projecti",
    twitchLink: "https://www.twitch.tv/dddsaur",
    vedioLId: "paIBS4bJlgE?si=Qg4pLT2HW0XKU2Jh",
  },
];

export default TalentData;
