export const TalentData = [
  {
    id: "honey-churros",
    name: "허니츄러스",
    enName: "HoneyChurros",
    profileImages: ["profile-ohwayo-1", "profile-ohwayo-2", "profile-ohwayo-3"],
    personalColor: "#ffd8d9",
    xLink: "",
    youtubeLink: "",
    twitchLink: "",
    vedioLId: "",
  },
  {
    id: "ohwayo",
    name: "오화요",
    enName: "Ohwayo",
    profileImages: ["profile-ohwayo-1", "profile-ohwayo-2", "profile-ohwayo-3"],
    personalColor: "#8c8c8c",
    xLink: "https://twitter.com/oi52ohighyo",
    youtubeLink: "https://www.youtube.com/@Ohwayo_Projecti",
    twitchLink: "https://www.twitch.tv/oi52ohighyo",
    vedioLId: "SJDnBrMAVSw?si=kHlXeF9Y71ZMEl67",
  },
  {
    id: "dam-yui",
    name: "담유이",
    enName: "DamYui",
    profileImages: ["profile-ohwayo-1", "profile-ohwayo-2", "profile-ohwayo-3"],
    personalColor: "#B7E8FF",
    xLink: "",
    youtubeLink: "",
    twitchLink: "",
    vedioLId: "",
  },
  {
    id: "aya-uke",
    name: "아야",
    enName: "AyaUke",
    profileImages: ["profile-ohwayo-1", "profile-ohwayo-2", "profile-ohwayo-3"],
    personalColor: "#D1AFE3",
    xLink: "",
    youtubeLink: "",
    twitchLink: "",
    vedioLId: "",
  },
  {
    id: "mang-nae",
    name: "망내",
    enName: "MangNae",
    profileImages: ["profile-ohwayo-1", "profile-ohwayo-2", "profile-ohwayo-3"],
    personalColor: "#000000",
    xLink: "",
    youtubeLink: "",
    twitchLink: "",
    vedioLId: "",
  },
  {
    id: "ddddragon",
    name: "디디디용",
    enName: "DDDDragon",
    profileImages: ["profile-ohwayo-1", "profile-ohwayo-2", "profile-ohwayo-3"],
    personalColor: "#FFBF00",
    xLink: "",
    youtubeLink: "",
    twitchLink: "",
    vedioLId: "",
  },
];
